name: Build and Test

on:
  push:
    branches: [main]

env:
  PACKAGE_NAME_LONG:  vcpkg-export-20220826-200052.1.0.0
  PACKAGE_NAME_SHORT: vcpkg-export-20220826-200052

jobs:
  build_test:
    name: build and test
    runs-on: windows-2019
    environment: packaging
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install boost-test
      env:
        REMOTE_STORE: "https://nuget.pkg.github.com/michaeltryby/index.json"
        USERNAME: michaeltryby
      run: |
        mkdir build
        cd build
        nuget sources add -Name github -Source ${{ env.REMOTE_STORE }} -Username ${{ env.USERNAME }} -Password ${{ secrets.ACCESS_TOKEN }}
        nuget install ${{env.PACKAGE_NAME_SHORT}} -Source github

    - name: Build
      env:
        TOOL_CHAIN_PATH: \scripts\buildsystems\vcpkg.cmake
      run: |
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=.\${{env.PACKAGE_NAME_LONG}}\scripts\buildsystems\vcpkg.cmake
        cmake --build .

    - name: Test
      run: build\test\Debug\first_test.exe
